# Minimal MongoBouncer Configuration for Testing
# This is the absolute minimum configuration needed to run MongoBouncer

[mongobouncer]
listen_addr = "0.0.0.0"
listen_port = 27017
log_level = "info"      # debug

# Connection management
pool_mode = "statement"
max_client_conn = 0

# MongoDB client pool settings (defaults for all databases)
max_pool_size = 20              # MongoDB driver's internal pool size
min_pool_size = 3               # MongoDB driver's minimum pool size
max_conn_idle_time = "30s"      # How long to keep idle connections
server_selection_timeout = "5s" # Server selection timeout
connect_timeout = "5s"          # Connection establishment timeout
socket_timeout = "30s"          # Socket operation timeout
heartbeat_interval = "10s"      # Heartbeat frequency
auth_enabled = false
regex_credential_passthrough = false
topology = "sharded"

# Prometheus metrics (optional but recommended)
metrics_address = "0.0.0.0:9090"
metrics_enabled = true

# Database connections - Configure these for your MongoDB setup
# Application databases - wildcard route for all databases

[databases."*"]
connection_string = "mongodb://127.0.0.1:27023/default?retryWrites=false"
topology = "single"

[databases.mongobouncer_test]
connection_string = "mongodb://localhost:27022/mongobouncer_test"
topology = "single"

[databases.pool_test]
connection_string = "mongodb://localhost:27022/pool_test"
max_pool_size = 10
min_pool_size = 10
socket_timeout = "60s"

# Database-specific MongoDB client overrides (optional)
[databases.high_traffic_db]
connection_string = "mongodb://localhost:27022/high_traffic_db"
max_pool_size = 50                                              # Override default for high-traffic database
min_pool_size = 10                                              # Override default
socket_timeout = "60s"                                          # Longer timeout for this DB

[databases.analytics_db]
connection_string = "mongodb://localhost:27022/analytics_db"
max_pool_size = 5                                            # Smaller pool for analytics
heartbeat_interval = "30s"                                   # Less frequent heartbeats

[databases.app_prod_rs8]
connection_string = "mongodb://appuser_rs8:apppass_rs8_123@host.docker.internal:27019/app_prod_rs8?replicaSet=rs1&authSource=admin"
topology = "sharded"

[databases.exact_db]
# Exact match database - will use route credentials (no passthrough)
connection_string = "mongodb://admin:admin123@localhost:27022/exact_db?authSource=admin"
label = "exact_match_database"

[databases."test_*"]
# Wildcard pattern - will use client credentials for downstream connections
connection_string = "mongodb://localhost:27022"
label = "test_wildcard_pattern"
